### ISSUE TITLE
QA pair dataset - answer retrieval

### ISSUE THREAD

**Issue by sanjay-391** [14H034160212/HHH-An-Online-Question-Answering-System-for-Medical-Questions#1]
Hi, i didnt find the implementation for the retrieval of answers from QA pair using the HBAM. In paper its seen that, when the answer is not found in KB, the answer is fetched from the QA pair dataset using the top k similar questions using HBAM

**Comment by 14H034160212** [comment]
Hi, 

We presented and implemented a medical sentence similarity calculation model called HBAM. We proposed a framework to use the HBAM for retrieving answers from QA pairs using HBAM if the question has not been found in the knowledge graph. But in this paper, we only designed the framework that a solution to use our HBAM is to fetch answers from the QA pair dataset using the top k similar questions using HBAM, but we did not put any experiment results for retrieving answers from the QA pair using HBAM. We evaluate whether our model is better than other medical sentence similarity models (Bi-LSTM+Attention, BERT, MaLSTM) on a medical sentence pairs dataset filtered out from Quora duplicate questions dataset.
