### ISSUE TITLE
How to run code locally

### ISSUE THREAD

**Issue by Muzammil-Elahi** [14H034160212/HHH-An-Online-Question-Answering-System-for-Medical-Questions#2]
Good afternoon, I would like to run the code locally. Which file should I run to start the GUI? Is there anything I have to do besides loading the data into the database?

**Comment by 14H034160212** [comment]
Hi, 

Thanks for your interest in this project. In this project, we establish a new medical sentence similarity computation model called HBAM. 

You can follow the installation step in the readme file as following shown.

```
conda create -n hhh python=3.6
conda activate hhh
git clone https://github.com/14H034160212/HHH-An-Online-Question-Answering-System-for-Medical-Questions.git
cd HHH-An-Online-Question-Answering-System-for-Medical-Questions
pip install -r requirements.txt
```

Then you can run the experiment inside each folder ([BERT_fine_tuning](https://github.com/14H034160212/HHH-An-Online-Question-Answering-System-for-Medical-Questions/tree/master/BERT_fine_tuning), [BiLSTM+Attention](https://github.com/14H034160212/HHH-An-Online-Question-Answering-System-for-Medical-Questions/tree/master/BiLSTM%2BAttention), [HBAM](https://github.com/14H034160212/HHH-An-Online-Question-Answering-System-for-Medical-Questions/tree/master/HBAM), and [MaLSTM](https://github.com/14H034160212/HHH-An-Online-Question-Answering-System-for-Medical-Questions/tree/master/MaLSTM)). I list the exact step and needed packages to run the code. 

**Medical Knowledge Graph Establish, GUI and website**
The main code is based on the following link. You need to run the build_medicalgraph.py to establish the knowledge graph before you use it. Then you may run GUI.py to run the GUI interface. You can also run chatbot_graph.py which will allow you to chat in command. You can also run server.py to start the website and chat. 
https://github.com/14H034160212/HHH-An-Online-Question-Answering-System-for-Medical-Questions/tree/master/Medical_knowledge_graph_establishment/MedicalKBQA
